services:
  postgres:
    image: postgres:16
    container_name: course-postgres
    environment:
      POSTGRES_DB: springboot_course
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d springboot_course"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: course-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springboot_course
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data:
